### ISSUE TITLE
Tiny improvement to performance

### ISSUE THREAD

**Issue by staltz** [yoshuawuyts/nanotask#1]
Just in case you're interested in squeezing this package a bit more:

`i = 1 - i` is faster than `i = ++i % 2` on Safari and Firefox, while being basically the same on Chrome.

<img width="550" alt="screen shot 2017-09-27 at 19 05 17" src="https://user-images.githubusercontent.com/90512/30924262-e8789912-a3b6-11e7-84f4-2605942739a2.png">

https://jsperf.com/bit-flip/1

- - -

And 

```js
for (var i = 0; i < queue.length; i++) queue[i]()
queue = []
```

changed to

```js
while (queue.length) queue.shift()()
```

saves us from reallocating a new array, and saves in code size.

Should be a bit faster too

<img width="714" alt="screen shot 2017-09-27 at 19 12 38" src="https://user-images.githubusercontent.com/90512/30924660-15609172-a3b8-11e7-8696-632112029aa3.png">

https://jsperf.com/array-realloc/1

But I'm not so confident the jsperf in this case correctly reflects what happens in nanotask.

**Comment by yoshuawuyts** [comment]
Oh, PRs to add all of these would be super neat. I don't really use this module at the moment; adding you as a collab so you can push if you want (:

**Comment by staltz** [comment]
Nice!
I actually copy-pasted it, and modified its purpose a bit because I need it to cover node.js too. Do you mind if nanotask works for both browsers and node? It wouldn't add that much more code, just another `if` branch.

**Comment by yoshuawuyts** [comment]
Yeah, sounds great! :D

**Comment by staltz** [comment]
Fixed this, you can issue a new version if you want :)
